sudo: false
language: node_js
node_js:
#  - "10"
#  - "8"
  - "6"
install:
  - yarn
script:
  - yarn coverage

env:
  global:
    - CC_TEST_REPORTER_ID=8277f64d4123c1ec9bafeb8c2db8a72403277f27a1419f944d013951318db00e

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache: yarn
