os: Visual Studio 2017
platform: x64
environment:
  matrix:
    - nodejs_version: "14"
    - nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn install --frozen-lockfile

test_script:
  - node --version
  - yarn --version
  - yarn e2e

build: off
deploy: off

cache:
  - node_modules -> appveyor.yml,yarn.lock
